name: Production Deployment Workflow
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash     
jobs:
  deploy_production:
    environment: production
    name: 'Deploy to Production'
    runs-on: ubuntu-latest
    steps:
     - uses: robinraju/release-downloader@v1.8
       with:
         latest: true
         fileName: "hello-world-maven.war"
     - name: Set up SSH
       uses: webfactory/ssh-agent@v0.8.0
       with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

     - name: Copy Files to Azure VM
       run: scp -o StrictHostKeyChecking=no -r hello-world-maven.war ${{ secrets.REMOTE_USER }}@${{ secrets.HOSTNAME }}:/opt/tomcat
