name: Production Deployment Workflow
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash     
jobs:
  deploy_production:
    environment: production
    name: 'Deploy to Production'
    runs-on: ubuntu-latest
    steps:
     - uses: robinraju/release-downloader@v1.8
       with:
         latest: true
         fileName: "hello-world-maven.war"
    
