name: Staging Deployment Workflow
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash     
jobs:
  deploy_staging:
    environment: staging
    name: 'Deploy to staging'
    runs-on: self-hosted
    steps:
     - uses: robinraju/release-downloader@v1.8
       with:
         latest: true
         fileName: "hello-world-maven.war"
     - name: Copy file
       run: cp /home/finalopenshift/actions-runner/_work/Demo1/Demo1/hello-world-maven.war /home/finalopenshift/stagingtomcat/apache-tomcat-8.5.96/webapps/.
     - name: Starting Tomcat 
       run: /home/finalopenshift/stagingtomcat/apache-tomcat-8.5.96/bin/startup.sh
     
