name: Continuous Integration Workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main    
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
     - uses: robinraju/release-downloader@v1.8
       with:
         latest: true
         fileName: "hello-world-maven.war"
