name: Staging Deployment Workflow
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash     
jobs:
  deploy_staging:
    environment: staging
    name: 'Deploy to staging'
    runs-on: self-hosted
    steps:
     - uses: robinraju/release-downloader@v1.8
       with:
         latest: true
         fileName: "hello-world-maven.war"

     
