name: Staging Deployment Workflow
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash     
jobs:
  deploy_staging:
    environment: staging
    name: 'Deploy to staging'
    runs-on: self-hosted
    steps:
     - uses: robinraju/release-downloader@v1.8
       with:
         latest: true
         fileName: "hello-world-maven.war"
     - name: Copy file
       uses: canastro/copy-action@0.0.2
       with:
         source: /home/finalopenshift/actions-runner/_work/Demo1/Demo1/hello-world-maven.war
         target: /home/finalopenshift/stagingtomcat/apache-tomcat-8.5.96/webapps/   

     
