name: Staging Deployment Workflow
on:
  workflow_dispatch:
     
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
     - uses: robinraju/release-downloader@v1.8
       with:
         latest: true
         fileName: "hello-world-maven.war"
