name: Continuous Integration Workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main    
jobs:
  run-Maven-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yuzhiyongcn/setup-maven@v1.0.0
        with:
          maven-version: 3.8.2
       
      - run: mvn clean install
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ GITHUB_ACTION_PATH }}/target/hello-world-maven.war
          asset_name: mything
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
      
