name: Continuous Integration Workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main    
jobs:
  run-Maven-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yuzhiyongcn/setup-maven@v1.0.0
        with:
          maven-version: 3.8.2
       
      - run: mvn clean install
      - uses: xresloader/upload-to-github-release@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "target/hello-world-maven.war"
          tag_name: "demotag" 
          overwrite: true
      
      
